---------------
--- GETTERS ---
---------------

-- Returns grids part of a project
DROP FUNCTION IF EXISTS get_grids;
CREATE FUNCTION get_grids(project_id INT)
RETURNS TABLE(taskid INTEGER, geom GEOMETRY) AS $$
BEGIN
	RETURN QUERY
	SELECT g.taskid, g.geom
	FROM grids g
	WHERE g.project_id = get_grids.project_id;
END;
$$ LANGUAGE plpgsql;

-- Returns grids in UTM projection
DROP FUNCTION IF EXISTS get_grids_in_utm;
CREATE FUNCTION get_grids_in_utm(project_id INT, do_mockup_grid BOOLEAN DEFAULT FALSE)
RETURNS TABLE(taskid INTEGER, geom GEOMETRY) AS $$
BEGIN
	IF do_mockup_grid THEN
		RETURN QUERY
		SELECT mpg.taskid, mpg.geom FROM mockup_polygon_grids AS mpg
		WHERE mpg.project_id = get_grids_in_utm.project_id;
	ELSE
		RETURN QUERY
		SELECT g.taskid, g.geom_utm FROM grids g
		WHERE g.project_id = get_grids_in_utm.project_id;
	END IF;
END;
$$ LANGUAGE plpgsql;


-- Returns shrunk grids in UTM projection
DROP FUNCTION IF EXISTS get_shrunk_grids_in_utm;
CREATE FUNCTION get_shrunk_grids_in_utm(project_id INT, shrink_distance DOUBLE PRECISION, grid_type TEXT DEFAULT 'ORIGINAL', is_percentage boolean DEFAULT FALSE)
RETURNS TABLE(gid INTEGER, taskid INTEGER, geom GEOMETRY) AS $$
DECLARE
	do_mockup_grid BOOLEAN;
BEGIN
	IF grid_type = 'MOCKUP-POLY' THEN
		IF NOT is_percentage THEN
			RAISE EXCEPTION 'Mockup polygon grids are only generated by percentage';
		END IF;

		RETURN QUERY
		WITH utm_grids AS (
			SELECT 0 as gid, ggiu.taskid, ggiu.geom
			FROM get_grids_in_utm(project_id, FALSE) AS ggiu
		),
		mockup_poly_grids AS (
			SELECT mpg.taskid, ST_Union(mpg.geom) AS geom
			FROM mockup_polygon_grids AS mpg
			WHERE mpg.project_id = get_shrunk_grids_in_utm.project_id
			AND mpg.percentage_covered = shrink_distance
			GROUP BY mpg.taskid
		)
		SELECT ug.gid, ug.taskid, ST_Difference(ug.geom, mg.geom) AS geom
		FROM utm_grids ug
		JOIN mockup_poly_grids mg ON ug.taskid = mg.taskid;
	ELSE
		IF grid_type = 'MOCKUP' THEN
			do_mockup_grid := TRUE;
		ELSE
			do_mockup_grid := FALSE;
		END IF;

		RETURN QUERY
		WITH utm_grids AS (
			SELECT 0 as gid, ggiu.taskid, ggiu.geom
			FROM get_grids_in_utm(project_id, do_mockup_grid) AS ggiu
		)
		SELECT utm_grids.gid, utm_grids.taskid, shrink_geometry(utm_grids.geom, shrink_distance, is_percentage) AS geom
		FROM utm_grids;
	END IF;
END;
$$ LANGUAGE plpgsql;

-- Returns roads part of a project
DROP FUNCTION IF EXISTS get_roads;
CREATE FUNCTION get_roads(project_id INT)
RETURNS TABLE(osm_id INTEGER, geom GEOMETRY) AS $$
BEGIN
	RETURN QUERY
	SELECT r.osm_id, r.geom
	FROM roads r
	WHERE r.project_id = get_roads.project_id;
END;
$$ LANGUAGE plpgsql;

-- Get buildings part of one or more tasks
DROP FUNCTION IF EXISTS get_buildings_from_tasks;
CREATE FUNCTION get_buildings_from_tasks(project_id INT, task_ids INT[])
RETURNS TABLE(osm_id INTEGER, geom GEOMETRY) AS $$
BEGIN
	RETURN QUERY
	SELECT b.osm_id, b.geom
	FROM buildings_utm b
	WHERE b.project_id = get_buildings_from_tasks.project_id
	AND EXISTS (
		SELECT 1
		FROM get_grids_in_utm(get_buildings_from_tasks.project_id) hg
		WHERE hg.taskid = ANY(get_buildings_from_tasks.task_ids)
		AND ST_Intersects(b.geom, hg.geom)
	);
END $$ LANGUAGE plpgsql;

-- Returns an accurate UTM zone number for a given project
DROP FUNCTION IF EXISTS get_utm_zone;
CREATE FUNCTION get_utm_zone(project_id INT)
RETURNS INT AS $$
DECLARE
	utm_epsg INTEGER;
BEGIN
	SELECT uz.utm_epsg INTO utm_epsg FROM utm_zones uz WHERE uz.project_id = get_utm_zone.project_id;

	IF utm_epsg IS NOT NULL THEN
		RETURN utm_epsg;
	END IF;

	-- Calculate the UTM EPSG code
	SELECT calculate_utm_zone(union_gg.geom)::INTEGER INTO utm_epsg
	FROM (
    	SELECT ST_Union(CASE WHEN ST_IsValid(gg.geom) THEN gg.geom ELSE ST_MakeValid(gg.geom) END) AS geom
    	FROM get_grids(project_id) AS gg
	) AS union_gg
	LIMIT 1;

	INSERT INTO utm_zones (utm_epsg, project_id) VALUES (utm_epsg, project_id);

	RETURN utm_epsg;
END;
$$ LANGUAGE plpgsql;

----------------
--- GEOMETRY ---
----------------

-- Attempts to fix the given polygon geometry
DROP FUNCTION IF EXISTS fix_geometry;
CREATE FUNCTION fix_geometry(input_geom GEOMETRY)
RETURNS GEOMETRY AS $$
DECLARE
	valid_geom GEOMETRY;
BEGIN
	-- Check if the input geometry is valid, otherwise fix it
	IF ST_IsValid(input_geom) THEN
			valid_geom := input_geom;
	ELSE
		RAISE NOTICE 'Input geometry is invalid, fixing geometry';
		valid_geom := ST_MakeValid(input_geom);

		FOR i IN 1..10 LOOP
			IF GeometryType(valid_geom) IN ('POLYGON', 'MULTIPOLYGON') THEN
				EXIT;
			ELSIF GeometryType(valid_geom) = 'GEOMETRYCOLLECTION' THEN
				-- Extract only the Polygon or MultiPolygon geometries from the collection
				valid_geom := (
					SELECT ST_Collect(valid_geoms.geom) -- Re-collect into a single geometry
					FROM (
						SELECT dumped_geom.geom
						FROM ST_Dump(valid_geom) AS dumped_geom
						WHERE GeometryType(dumped_geom.geom) IN ('POLYGON', 'MULTIPOLYGON')
					) AS valid_geoms
				);
			ELSIF GeometryType(valid_geom) = 'MULTILINESTRING' THEN
				-- Convert MultiLineString to Polygon or Multipolygon
				valid_geom := ST_Polygonize(valid_geom);
			END IF;
		END LOOP;
	END IF;
	IF GeometryType(valid_geom) IN ('POLYGON', 'MULTIPOLYGON') THEN
		RETURN valid_geom;
	END IF;
	RAISE NOTICE 'Returning NULL. Failed to fix geometry: %', ST_AsText(input_geom);
	RETURN NULL;
END $$ LANGUAGE plpgsql;

-- -- Generates mockup grids
-- DROP FUNCTION IF EXISTS generate_grid;
-- CREATE FUNCTION generate_grid(input_geom geometry, x_width DOUBLE PRECISION, y_height DOUBLE PRECISION)
-- RETURNS TABLE (id INT, geom geometry(POLYGON)) AS $$
-- DECLARE
-- 	minx DOUBLE PRECISION;
-- 	miny DOUBLE PRECISION;
-- 	maxx DOUBLE PRECISION;
-- 	maxy DOUBLE PRECISION;
-- 	x DOUBLE PRECISION;
-- 	y DOUBLE PRECISION;
-- 	grid_id integer := 0;
-- 	grid_cell geometry;
-- 	srid integer;
-- BEGIN
-- 	-- Get the bounding box of the input geometry
-- 	SELECT
--     	ST_XMin(input_geom),
--     	ST_YMin(input_geom),
--     	ST_XMax(input_geom),
--     	ST_YMax(input_geom)
-- 	INTO
--     	minx,
--     	miny,
--     	maxx,
--     	maxy;

-- 	SELECT ST_SRID(input_geom) INTO srid;

-- 	-- Generate the grid cells and return them
-- 	x := minx;
-- 	WHILE x < maxx LOOP
--     	y := miny;
--     	WHILE y < maxy LOOP
--         	grid_id := grid_id + 1;
--         	grid_cell := ST_SetSRID(
--                         	ST_MakePolygon(
--                             	ST_MakeLine(ARRAY[
--                                 	ST_Point(x, y),
--                                 	ST_Point(x + x_width, y),
--                                 	ST_Point(x + x_width, y + y_height),
--                                 	ST_Point(x, y + y_height),
--                                 	ST_Point(x, y)
--                             	])
--                         	), srid
--                     	);
--         	geom := ST_Intersection(grid_cell, input_geom);
--         	IF NOT ST_IsEmpty(geom) THEN
--             	id := grid_id;
--             	RETURN NEXT;
--         	END IF;
--         	y := y + y_height;
--     	END LOOP;
--     	x := x + x_width;
-- 	END LOOP;
-- END $$ LANGUAGE plpgsql;

-- -- Generates mockup grid with project_id
-- DROP FUNCTION IF EXISTS generate_mockup_grid;
-- CREATE FUNCTION generate_mockup_grid(project_id INT)
-- RETURNS TABLE (id INT, geom geometry(POLYGON)) AS $$
-- DECLARE
-- 	x_width DOUBLE PRECISION := 0.01;
-- 	y_height DOUBLE PRECISION := 0.01;
-- BEGIN
-- 	RETURN QUERY
-- 	SELECT 0 AS id, geng.geom
-- 	FROM generate_grid(
-- 		(
-- 			SELECT ST_Union(vg.geom) FROM (
-- 				SELECT 
-- 					CASE 
-- 						WHEN ST_IsValid(gg.geom) THEN gg.geom 
-- 						ELSE ST_MakeValid(gg.geom) 
-- 					END AS geom
-- 				FROM get_grids(project_id, FALSE) AS gg
-- 			) AS vg
-- 		),
-- 		x_width,
-- 		y_height
-- 	) AS geng;
-- END;
-- $$ LANGUAGE plpgsql;

-- Returns an accurate UTM zone number for a given geometry
DROP FUNCTION IF EXISTS calculate_utm_zone;
CREATE FUNCTION calculate_utm_zone(geometry GEOMETRY)
RETURNS TEXT AS $$
DECLARE
	lat NUMERIC;
	lon NUMERIC;
	zone_number INT;
	epsg_number TEXT;
BEGIN
	-- Calculate the centroid of the bounding box of the geometry
	SELECT ST_Y(ST_Centroid(ST_Extent(geometry))), ST_X(ST_Centroid(ST_Extent(geometry)))
	INTO lat, lon;

	-- Calculate the UTM zone number
	zone_number := FLOOR((lon + 180) / 6) + 1;

	-- Determine the EPSG code based on latitude
	IF lat >= 0 THEN
    	epsg_number := '326' || LPAD(zone_number::TEXT, 2, '0');
	ELSE
    	epsg_number := '327' || LPAD(zone_number::TEXT, 2, '0');
	END IF;

	RETURN epsg_number;
END;
$$ LANGUAGE plpgsql;

-- Shrinks a geometry by a given distance or percentage
DROP FUNCTION IF EXISTS shrink_geometry;
CREATE FUNCTION shrink_geometry(
    geom geometry, 
    shrink_value double precision, 
    is_percentage boolean DEFAULT FALSE
)
RETURNS geometry AS $$
DECLARE
    scaled_geom geometry;
    scale_factor double precision;
BEGIN

	IF shrink_value = 0 OR ST_Area(geom) = 0 THEN
		RETURN geom;
	END IF;

    IF is_percentage THEN
		IF shrink_value = 100 THEN
			RETURN ST_MakeEmpty();
		END IF;

        -- Convert percentage to a factor between 0 and 1
        scale_factor := 1 - (shrink_value / 100.0);
        
        -- Dilate back the geometry by the scale factor
        scaled_geom := ST_Dilate(geom, scale_factor);
    ELSE
        -- Apply the negative buffer to shrink the geometry by a fixed distance
        scaled_geom := ST_Buffer(geom, -shrink_value);
    END IF;

    RETURN scaled_geom;
END;
$$ LANGUAGE plpgsql;


-- Returns true if all grids are fully adjacent and not overlapping
DROP FUNCTION IF EXISTS project_has_fully_adjacent_cells;
CREATE FUNCTION project_has_fully_adjacent_cells(project_id INT)
RETURNS BOOLEAN AS $$
DECLARE
	num_clusters INT;
	overlapping_count INT;
BEGIN
	-- Count the number of unique clusters where geometries intersect
	SELECT COUNT(DISTINCT cluster) INTO num_clusters
	FROM (
		SELECT
			unnest(ST_ClusterIntersecting(geom)) AS cluster
		FROM (
			SELECT 
				CASE 
					WHEN ST_IsValid(geom) THEN geom 
					ELSE ST_MakeValid(geom) 
				END AS geom
			FROM get_grids(project_id)
		) AS valid_geoms
	) AS clustered_areas;

	-- Count the number of overlapping geometries
	SELECT COUNT(*) INTO overlapping_count
	FROM (
		SELECT g1.geom
		FROM (
			SELECT 
				CASE 
					WHEN ST_IsValid(geom) THEN geom 
					ELSE ST_MakeValid(geom) 
				END AS geom, taskid
			FROM get_grids(project_id)
		) g1, (
			SELECT 
				CASE 
					WHEN ST_IsValid(geom) THEN geom 
					ELSE ST_MakeValid(geom) 
				END AS geom, taskid
			FROM get_grids(project_id)
		) g2
		WHERE g1.taskid <> g2.taskid AND ST_Overlaps(g1.geom, g2.geom)
	) AS overlapping_areas;

	-- Return true if all geometries are in a single cluster and there are no overlaps, otherwise false
	RETURN num_clusters = 1 AND overlapping_count = 0;
END;
$$ LANGUAGE plpgsql;

-- Returns task ids of the adjacent tasks
DROP FUNCTION IF EXISTS get_adjacent_tasks;
CREATE FUNCTION get_adjacent_tasks(project_id INT, task_id INT)
RETURNS TABLE(adjacent_task_id INTEGER) AS $$
BEGIN
	RETURN QUERY
	SELECT adt.adjacent_task_id
	FROM adjacent_tasks adt
	WHERE adt.project_id = get_adjacent_tasks.project_id
	AND adt.task_id = get_adjacent_tasks.task_id;
END $$ LANGUAGE plpgsql;

-- Divides a grid cell into subpolygons with a target area, with n being the number of points created for the random polygons and m being the target area percentage
DROP FUNCTION IF EXISTS divide_polygon;
CREATE OR REPLACE FUNCTION divide_polygon(input_geom GEOMETRY, n INTEGER, m DOUBLE PRECISION)
RETURNS TABLE(geom GEOMETRY) AS $$
DECLARE
    valid_geom GEOMETRY;
	total_area NUMERIC;
    target_total_area NUMERIC;
    accumulated_area NUMERIC := 0;
    remaining_area NUMERIC;
    selected_geom GEOMETRY;
	selected_geom_old GEOMETRY;
    voronoi_geoms GEOMETRY[];
    voronoi_ids INTEGER[];
    i INTEGER;
    j INTEGER;
    temp_geom GEOMETRY;
    temp_id INTEGER;
	dilate_tolerance DOUBLE PRECISION;
	dilate_tolerance_factor_of_area DOUBLE PRECISION := 100000;
	dilate_guess DOUBLE PRECISION;
	dilate_guess_factor_of_area DOUBLE PRECISION := 100000;
	dilate_safety INTEGER := 1000000000;
BEGIN

	-- Check if the input geometry is valid, otherwise fix it
	IF ST_IsValid(input_geom) THEN
			valid_geom := input_geom;
	ELSE
		RAISE NOTICE 'Input geometry is invalid, fixing geometry';
		valid_geom := ST_MakeValid(input_geom);

		IF GeometryType(valid_geom) = 'GEOMETRYCOLLECTION' THEN
            -- Extract only the Polygon or MultiPolygon geometries from the collection
            valid_geom := (
                SELECT ST_Collect(valid_geoms.geom) -- Re-collect into a single geometry
                FROM (
                    SELECT dumped_geom.geom
                    FROM ST_Dump(valid_geom) AS dumped_geom
                    WHERE GeometryType(dumped_geom.geom) IN ('POLYGON', 'MULTIPOLYGON')
                ) AS valid_geoms
            );
        END IF;
	END IF;
	-- Step 1: Calculate the total area of the input polygon
	total_area := ST_Area(valid_geom);

	IF total_area = 0 THEN
		RAISE NOTICE 'Input geometry has zero area';
		RETURN;
	END IF;

	-- Set tolerance and guess for ST_Dilate
	dilate_tolerance := total_area / dilate_tolerance_factor_of_area;
	dilate_guess := total_area / dilate_guess_factor_of_area;

    -- Step 2: Determine the target total area for all subpolygons combined
    target_total_area := (m / 100.0) * total_area;

    -- Step 3: Generate Voronoi polygons from random points within the polygon
    SELECT array_agg(clipped_voronoi.geom) INTO voronoi_geoms
    FROM (
        SELECT ST_Intersection(v.geom, valid_geom) AS geom
        FROM (
            SELECT (ST_Dump(ST_VoronoiPolygons(ST_Collect(random_points.geom)))).geom AS geom
            FROM (SELECT ST_GeneratePoints(valid_geom, n) AS geom) AS random_points
        ) AS v
    ) AS clipped_voronoi;

    -- Initialize an array of indices for shuffling
    SELECT array(SELECT generate_series(1, array_length(voronoi_geoms, 1))) INTO voronoi_ids;

	IF voronoi_ids IS NOT NULL AND array_length(voronoi_ids, 1) > 0 THEN
	    FOR i IN array_lower(voronoi_ids, 1) .. array_upper(voronoi_ids, 1) LOOP
			j := floor(random() * (array_length(voronoi_ids, 1) - i + 1) + i)::integer;
			temp_id := voronoi_ids[i];
			voronoi_ids[i] := voronoi_ids[j];
			voronoi_ids[j] := temp_id;
		END LOOP;

		-- Step 4: Iterate through shuffled Voronoi polygons
		i := 1;
		WHILE i <= array_length(voronoi_ids, 1) AND accumulated_area < target_total_area LOOP
			selected_geom := voronoi_geoms[voronoi_ids[i]];
			accumulated_area := accumulated_area + ST_Area(selected_geom);

			-- If the accumulated area exceeds the target, clip the last polygon to fit the exact area
			IF accumulated_area > target_total_area THEN
				selected_geom_old := selected_geom;
				selected_geom := ST_Dilate(
					selected_geom_old,
					(target_total_area - (accumulated_area - ST_Area(selected_geom_old))) / ST_Area(selected_geom_old),
					tol => dilate_tolerance,
					guess => dilate_guess,
					safety => dilate_safety
					);

				-- If ST_Dilate fails, return the original geometry
				IF selected_geom IS NULL THEN
					selected_geom := selected_geom_old;
					RAISE NOTICE 'Failed to dilate geometry, returning original geometry';
				END IF;

				accumulated_area := target_total_area;
			END IF;

			-- Return the selected geometry as a subpolygon
			geom := selected_geom;
			RETURN NEXT;
	

			-- Increment index
			i := i + 1;
		END LOOP;
	END IF;
END $$ LANGUAGE plpgsql;

-- Generates mockup polygon grid with project_id
DROP FUNCTION IF EXISTS generate_mockup_polygon_grid;
CREATE OR REPLACE FUNCTION generate_mockup_polygon_grid(project_id INT, percentage_covered DOUBLE PRECISION)
RETURNS TABLE (taskid INT, geom GEOMETRY) AS $$
DECLARE
	dividing_factor INTEGER := 100;
BEGIN
    -- Return a combined result set from divide_polygon for all grids
    RETURN QUERY
    SELECT
        subpolygon_lateral.taskid AS taskid,
        subpolygon_lateral.geom AS geom
    FROM get_grids_in_utm(project_id, FALSE) AS grid,
    LATERAL (
        SELECT subpolygon.geom, grid.taskid
        FROM divide_polygon(
            input_geom => grid.geom,
            n => dividing_factor,
            m => percentage_covered
        ) AS subpolygon
    ) AS subpolygon_lateral;
END $$ LANGUAGE plpgsql;
